[project]
name = "simple"
version = "0.1.0"
dependencies = [
    "pytest>=9.0.2",
    "requests>=2.32.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]
